[[redirects]]
  from = "/*"
  to = "/server.js"
  status = 200

[[headers]]
  for = "/*"
  [headers.Access-Control-Allow-Origin]
  origin = "*"
  [headers.Access-Control-Allow-Methods]
  methods = "GET, POST, PUT, DELETE, OPTIONS"
  [headers.Access-Control-Allow-Headers]
  headers = "Content-Type, Authorization"
